# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\"Q\n\x0eRetrievedChunk\x12\r\n\x05score\x18\x01 \x01(\x02\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t\"o\n\x17GenerateResponseRequest\x12\x12\n\nuser_query\x18\x01 \x01(\t\x12*\n\x11retrieved_content\x18\x02 \x03(\x0b\x32\x0f.RetrievedChunk\x12\x14\n\x0cmemory_block\x18\x03 \x01(\t\"h\n\x15GenerateResponseReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x11\n\tfollow_up\x18\x02 \x01(\t\x12\x15\n\rdocument_hits\x18\x03 \x03(\t\x12\x15\n\rresource_type\x18\x04 \x01(\t2R\n\nLLMService\x12\x44\n\x10GenerateResponse\x12\x18.GenerateResponseRequest\x1a\x16.GenerateResponseReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVEDCHUNK']._serialized_start=21
  _globals['_RETRIEVEDCHUNK']._serialized_end=102
  _globals['_GENERATERESPONSEREQUEST']._serialized_start=104
  _globals['_GENERATERESPONSEREQUEST']._serialized_end=215
  _globals['_GENERATERESPONSEREPLY']._serialized_start=217
  _globals['_GENERATERESPONSEREPLY']._serialized_end=321
  _globals['_LLMSERVICE']._serialized_start=323
  _globals['_LLMSERVICE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
