# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import llm_service_pb2 as llm__service__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateResponse = channel.unary_unary(
                '/LLMService/GenerateResponse',
                request_serializer=llm__service__pb2.GenerateResponseRequest.SerializeToString,
                response_deserializer=llm__service__pb2.GenerateResponseReply.FromString,
                _registered_method=True)
        self.AnalyzeContent = channel.unary_unary(
                '/LLMService/AnalyzeContent',
                request_serializer=llm__service__pb2.AnalyzeContentRequest.SerializeToString,
                response_deserializer=llm__service__pb2.AnalyzeContentReply.FromString,
                _registered_method=True)


class LLMServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateResponse,
                    request_deserializer=llm__service__pb2.GenerateResponseRequest.FromString,
                    response_serializer=llm__service__pb2.GenerateResponseReply.SerializeToString,
            ),
            'AnalyzeContent': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeContent,
                    request_deserializer=llm__service__pb2.AnalyzeContentRequest.FromString,
                    response_serializer=llm__service__pb2.AnalyzeContentReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LLMService/GenerateResponse',
            llm__service__pb2.GenerateResponseRequest.SerializeToString,
            llm__service__pb2.GenerateResponseReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LLMService/AnalyzeContent',
            llm__service__pb2.AnalyzeContentRequest.SerializeToString,
            llm__service__pb2.AnalyzeContentReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
