# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import embedding_pb2 as embedding__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """--------- Existing + new RPCs ---------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleUpload = channel.unary_unary(
                '/embedding.EmbeddingService/HandleUpload',
                request_serializer=embedding__pb2.HandleUploadRequest.SerializeToString,
                response_deserializer=embedding__pb2.HandleUploadResponse.FromString,
                _registered_method=True)
        self.GetEmbedding = channel.unary_unary(
                '/embedding.EmbeddingService/GetEmbedding',
                request_serializer=embedding__pb2.GetEmbeddingRequest.SerializeToString,
                response_deserializer=embedding__pb2.GetEmbeddingResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """--------- Existing + new RPCs ---------
    """

    def HandleUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """<-- NEW!
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleUpload,
                    request_deserializer=embedding__pb2.HandleUploadRequest.FromString,
                    response_serializer=embedding__pb2.HandleUploadResponse.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=embedding__pb2.GetEmbeddingRequest.FromString,
                    response_serializer=embedding__pb2.GetEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('embedding.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """--------- Existing + new RPCs ---------
    """

    @staticmethod
    def HandleUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/HandleUpload',
            embedding__pb2.HandleUploadRequest.SerializeToString,
            embedding__pb2.HandleUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/GetEmbedding',
            embedding__pb2.GetEmbeddingRequest.SerializeToString,
            embedding__pb2.GetEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
