# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\"Q\n\x13HandleUploadRequest\x12\x11\n\ttemp_path\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x15\n\roriginal_name\x18\x03 \x01(\t\"K\n\x14HandleUploadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nfinal_path\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"#\n\x13GetEmbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x14GetEmbeddingResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32\xb4\x01\n\x10\x45mbeddingService\x12O\n\x0cHandleUpload\x12\x1e.embedding.HandleUploadRequest\x1a\x1f.embedding.HandleUploadResponse\x12O\n\x0cGetEmbedding\x12\x1e.embedding.GetEmbeddingRequest\x1a\x1f.embedding.GetEmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDLEUPLOADREQUEST']._serialized_start=30
  _globals['_HANDLEUPLOADREQUEST']._serialized_end=111
  _globals['_HANDLEUPLOADRESPONSE']._serialized_start=113
  _globals['_HANDLEUPLOADRESPONSE']._serialized_end=188
  _globals['_GETEMBEDDINGREQUEST']._serialized_start=190
  _globals['_GETEMBEDDINGREQUEST']._serialized_end=225
  _globals['_GETEMBEDDINGRESPONSE']._serialized_start=227
  _globals['_GETEMBEDDINGRESPONSE']._serialized_end=265
  _globals['_EMBEDDINGSERVICE']._serialized_start=268
  _globals['_EMBEDDINGSERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
