# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\"\x89\x01\n\x0eRetrievedChunk\x12\r\n\x05score\x18\x01 \x01(\x02\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t\x12\x0c\n\x04page\x18\x05 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x06 \x01(\x05\x12\x13\n\x0b\x64ocument_id\x18\x07 \x01(\t\"\x83\x01\n\x17GenerateResponseRequest\x12\x12\n\nuser_query\x18\x01 \x01(\t\x12*\n\x11retrieved_content\x18\x02 \x03(\x0b\x32\x0f.RetrievedChunk\x12\x14\n\x0cmemory_block\x18\x03 \x01(\t\x12\x12\n\nis_refusal\x18\x04 \x01(\x08\"\x80\x01\n\x15GenerateResponseReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x11\n\tfollow_up\x18\x02 \x01(\t\x12\x15\n\rdocument_hits\x18\x03 \x03(\t\x12\x15\n\rresource_type\x18\x04 \x01(\t\x12\x16\n\x0etelemetry_json\x18\x05 \x01(\t\"R\n\x15\x41nalyzeContentRequest\x12\x15\n\rsystem_prompt\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttask_type\x18\x03 \x01(\t\"=\n\x13\x41nalyzeContentReply\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x16\n\x0etelemetry_json\x18\x02 \x01(\t2\x92\x01\n\nLLMService\x12\x44\n\x10GenerateResponse\x12\x18.GenerateResponseRequest\x1a\x16.GenerateResponseReply\x12>\n\x0e\x41nalyzeContent\x12\x16.AnalyzeContentRequest\x1a\x14.AnalyzeContentReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVEDCHUNK']._serialized_start=22
  _globals['_RETRIEVEDCHUNK']._serialized_end=159
  _globals['_GENERATERESPONSEREQUEST']._serialized_start=162
  _globals['_GENERATERESPONSEREQUEST']._serialized_end=293
  _globals['_GENERATERESPONSEREPLY']._serialized_start=296
  _globals['_GENERATERESPONSEREPLY']._serialized_end=424
  _globals['_ANALYZECONTENTREQUEST']._serialized_start=426
  _globals['_ANALYZECONTENTREQUEST']._serialized_end=508
  _globals['_ANALYZECONTENTREPLY']._serialized_start=510
  _globals['_ANALYZECONTENTREPLY']._serialized_end=571
  _globals['_LLMSERVICE']._serialized_start=574
  _globals['_LLMSERVICE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
